<?php

$config['supported_locales'] = array(
		'en'=>array(
			'country'=>'us',
			'locale'=>'en',
			'lang'=>'en',
			'language'=>'en',
			'extra'=>array(
				'langbar'=>'global',
				'tinymce'=>'en',
			),
		),
		/*
		'zh'=>array(
			'country'=>'hk',
			'locale'=>'zh',
			'lang'=>'zh',
			'language'=>'zh',
			'extra'=>array(
				'langbar'=>'hk',
				'tinymce'=>'zh_TW',
				'facebook'=>'zh_HK',
			),
		),
		'tw'=>'zh',
		'hk-zh'=>'zh',
		'hk-en'=>'en',
		'hk'=>'zh',
		
		'zh_CN'=>'cn',
		'cn'=>array(
			'country'=>'cn',
			'locale'=>'cn',
			'lang'=>'zh',
			'language'=>'zh-cn',
			'p_locale'=>'zh_CN',
		),
		*/
);